### ISSUE TITLE
Rename Repo

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianGuardian-iOS#19]
As we’ll need to point people back to this source repo, the repo needs to be renamed. Probably GordianGuardian-Catalyst

**Comment by ChristopherA** [comment]
All the other iOS Gordian apps that are Multiplatform are named GordianX-Catalyst. `iOS-GordianGuardian` is not the convention.

I'm up for updating the convention if we really need to (though that will require some work so it needs to be justified).

**Comment by wolfmcnally** [comment]
Catalyst *is* iOS. And a separate repo for Catalyst builds is not necessary. I wish you had consulted me before taking this decision.

**Comment by wolfmcnally** [comment]
Actually for a given app, separate repos for *any* Apple platforms are unnecessary and counterproductive.

**Comment by ChristopherA** [comment]
Catalyst is both iOS & Mac. If it is iOS only, then *-iOS. If Mac only then *-macos. If both *-catalyst. If Android *-android.

**Comment by ChristopherA** [comment]
Also at issue is the name must be first, so that the different versions sort together.

**Comment by wolfmcnally** [comment]
Per our discussion, my recommendation is that a -catalyst suffix be reserved for repos that *only* build a catalyst target. Similarly, repos that *only* build a Mac-native (import AppKit) target should have the suffix -macOS. All other Apple-platform repos should have the suffix "-iOS" as this covers: iOS devices, the iOS simulator, Catalyst, Apple Watch, Apple TV, and most likely every other hardware platform Apple will introduce over the next several years.

In general there is never any reason to have separate repos for Catalyst builds, as the same codebase should be able to build for all Apple platforms, *including* if necessary a Mac-native (import AppKit) target. Codebases that use "import UIKit" or "import SwiftUI" should all have the suffix "-iOS" unless they are *strictly* Mac-native.

**Comment by wolfmcnally** [comment]
I will be renaming the Guardian repo to "GordianGuardian-iOS" after the next Text Flight release.

**Comment by wolfmcnally** [comment]
> Catalyst is both iOS & Mac. If it is iOS only, then *-iOS. If Mac only then *-macos. If both *-catalyst. If Android *-android.

I strongly disagree with this. Catalyst is iOS running *on* the Mac. iOS is: iPhone, iPad, Apple Watch, Apple TV, and Catalyst. A single Xcode project can include a single target that will build for iPhone, iPad, an Apple Watch Plugin, and Catalyst. You need a separate target if you're building for native macOS or Apple TV. Nonetheless, the `import UIKit` is used for *all* iOS targets, not all "Catalyst" targets. You are simply putting far too much emphasis on Catalyst when it is simply an enabling technology, like Rosetta, and not an entire platform. The platform is simply: iOS.

**Comment by wolfmcnally** [comment]
This is fixed.
