### ISSUE TITLE
Why 7 chars for seed fingerprint?

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianGuardian-iOS#28]
![PNG image](https://user-images.githubusercontent.com/69103/108134310-d78b3180-706a-11eb-9f1d-9ab10c8b250f.png)

Why is the seed fingerprint 7 chars? Convention everyplace else is hashes are abbreviated as being 8 chars, in Bitcoin, SSH, GPG, etc. I’ve tried to get used to it but it still bugs me.

**Comment by wolfmcnally** [comment]
Why not?

**Comment by wolfmcnally** [comment]
Convention for GitHub is 7 characters of a 128 bit hash, and programmers look at it all day.

**Comment by wolfmcnally** [comment]
7 characters also helps distinguish it from all those other fingerprints you're talking about. It should be a flag to anyone who thinks of what they're being shown in a habitual way.

**Comment by wolfmcnally** [comment]
And yet, it's still enough to provide an effective cross-check with the LifeHash.

**Comment by wolfmcnally** [comment]
Can we consider this settled?

**Comment by wolfmcnally** [comment]
Closing this for now. Re-open if/when we need to revisit it.
