### ISSUE TITLE
Use & Prominence of Seed Fingerprint 

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianGuardian-iOS#29]
![PNG image 2](https://user-images.githubusercontent.com/69103/108135617-436e9980-706d-11eb-9368-d6a617204432.png)

Given its prominence, is there anyone else we know of that used a seed fingerprint the same as we do?

Largely bitcoin wallets tend to map their seeds to the master fingerprint m/ to ease identification of descriptors and xpub/xprv to their seed. Thus no one will search for this fingerprint, and may be frustrated if they gave xpub/xprv and are trying to find their seed for it. I know Ethereum and others the m’ the same as Bitcoin.

I’m not saying it should has to go, but as no one else uses it, it is useless to search for it or sort on it, maybe it only belongs on detail screen? But I could definitely argue that the m/ fingerprint is also a hash and maybe we should just use that as the hash. At least it is useful to connect derivations back to their seed

**Comment by ChristopherA** [comment]
It is also possible the label should be on top.

**Comment by wolfmcnally** [comment]
The seed fingerprint is just as much as an identifier as the LifeHash. It should have equal prominence. Not all objects are expected to *have* names, and objects can have duplicate names. So making sure the identifier is prominent is the best security.

**Comment by ChristopherA** [comment]
I'm still not sure that functionally this fingerprint (a hash) is any better than using a fingerprint used in more places, the master key fingerprint (hash of a hash). 

My use case is that I'm trying to tie back back to key if I have a descriptor from another wallet or system. Right now if I see a public keyset, I can't find the seed so I can recreate the private keyset.

You might argue "well use both", my question is "why?" No one else uses our way of doing a fingerprint.

**Comment by wolfmcnally** [comment]
No one else uses a LifeHash. Should we stop?

**Comment by wolfmcnally** [comment]
The idea is to have a larger view of fingerprinting objects. The fingerprint is actually the SHA-256 that is used to *create* the LifeHash. And that hash, in the larger ecosystem, is created using different information from different objects. Seeds, keys, and other persistent objects will have similar fingerprints. We're not omitting anything from what we're showing for keys: we're still showing those fingerprints. But we're also showing how this object, whether it's a seed, a key, or anything else, fits into our greater ecosystem.

**Comment by wolfmcnally** [comment]
If you know the SHA that was used to create the LifeHash, then you can *recreate* the LifeHash anywhere, even without having the object that the SHA fingerprint came from. You *cannot* do that with a key fingerprint.

**Comment by wolfmcnally** [comment]
By *always* putting the SHA fingerprint in the same place and with large prominence like the LifeHash, we start to build a visual language that people can rely on. If we start changing it up depending on the type of object, it breaks the association with the LifeHash and the larger role it plays in our ecosystem.

**Comment by wolfmcnally** [comment]
I have now taken pains to document the way seeds and HDKeys should be fingerprinted. We'll do this for other objects in time, and I've laid down guidelines for how that should be done. You want to throw that away for HDKeys only just because they have a field that also happens to be called "fingerprint"? Our SHA does more than identify the key material: it also identifies, in the case of an HDKey, the chain code, the asset (coin type) and the network. If any of these change, the identity of the key also changes, and hence our fingerprint changes. This is *not* true for BIP32 fingerprints.

**Comment by wolfmcnally** [comment]
Think of the BIP32 fingerprint as like a car's license place and the SHA fingerprint as the car's VIN. The VIN encodes a lot more information and more uniquely identifies the car than does the license plate even before you correlate either number with registration or manufacturer databases. Imperfect analogy of course, but there is an important place for both.

**Comment by wolfmcnally** [comment]
Can we consider this settled?

**Comment by wolfmcnally** [comment]
@ChristopherA To avoid further confusion I'm giving thought to renaming the LifeHash fingerprint to something else, like "retina scan" or "passport" or something.

**Comment by wolfmcnally** [comment]
We've decided to call it the "digest" from now on, so I'm closing this.
