### ISSUE TITLE
Ethereum or Zcash here, not Bitcoin Cash

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianGuardian-iOS#33]
![PNG image 5](https://user-images.githubusercontent.com/69103/108136838-a06b4f00-706f-11eb-9f9b-ba42050e1d1f.png)

I think having Bitcoin Cash here may be misinterpreted. Let’s just put Ethereum or Zcash here as a placeholder for other coin types instead.  Both are more likely to fund us too.

**Comment by wolfmcnally** [comment]
OK.
