### ISSUE TITLE
Question: SSKR is SSSS rebranded?

### ISSUE THREAD

**Issue by henkvancann** [BlockchainCommons/GordianGuardian-iOS#37]
And if not maybe explain, because it sounds a lot like Shamir SSS
- [x] Add as an issue in github

🐺 Wolf: Under the hood SSKR is using the technique of Shamir's Secret Sharing (SSS) but SSKR is a particular packaging of that technique optimized for CBOR and URs. The question is whether that's worth explaining to most users.

| ===|  | =========================== | 
|---| -------- | ------------------------ | 
| | ![](https://i.imgur.com/SYpP0sK.png)     | |

**Comment by henkvancann** [comment]
^^: "Note for experts: SSKR is a particular..." ?

**Comment by wolfmcnally** [comment]
Not sure we actually need to be this explicit in this particular place. I've referred the question to Shannon.

**Comment by henkvancann** [comment]
Feel free, the term SSKR raised more questions than it answered in the app. That's way I thought a brief explanatory line could help. Novices get reluctant / scared of terms they don't comprehend? Google doesn't say anything about SSKR either yet.

**Comment by wolfmcnally** [comment]
@henkvancann SSKR itself is fully documented, which now comes up as the first hit on Google.

![image](https://user-images.githubusercontent.com/676176/115101498-81ffc380-9ef9-11eb-86bb-d5befea21076.png)

So I'm going to close this for now.

**Comment by shannona** [comment]
I've also got some explainers for developers and users which are pending release. I think those will help when we get them out, and SSKR documentation is generally on my this-week TODO-list, pending a few other priorities.
