### ISSUE TITLE
Flow: Test QRs on github - Seed request confusing on one device

### ISSUE THREAD

**Issue by henkvancann** [BlockchainCommons/GordianGuardian-iOS#40]
Test QRs here: https://github.com/BlockchainCommons/GordianGuardian-iOS/blob/master/Testing/DPAL%20Seed.pdf

Is it possible to know that this device manages this seed by itself. "Another device" is the same device.

🐺 @wolfmcnally : I'm not sure how to make this clearer. Typically "another device" **will note** be this device. If the requested seed is not already on the device, it obviously can't send it, and will tell you so. It also makes clear the consequences of sending the seed (via the QR Code) to another device.

The request URs available in the PDFs are so you can test a UR similar to what another device would show when requesting a seed from this device.

| ===|  | =========================== | 
|---| -------- | ------------------------ | 
| | ![](https://i.imgur.com/Q6mZv7I.png)     | |

**Comment by wolfmcnally** [comment]
I'm not sure how to make this clearer. Typically "another device" **will not** be this device. If the requested seed is not already on the device, it obviously can't send it, and will tell you so. It also makes clear the consequences of sending the seed (via the QR Code) to another device.

The request URs available in the PDFs are so you can test a UR similar to what another device would show when requesting a seed from this device.
