### ISSUE TITLE
Question: I can import the same seed twice

### ISSUE THREAD

**Issue by henkvancann** [BlockchainCommons/GordianGuardian-iOS#41]
I can't think of a reason why I would want to import the same seed twice.

🐺 @wolfmcnally : `ur:crypto-seed` contains metadata like name and notes that can be different. It's up to the user to reconcile these differences.

| ===|  | =========================== | 
|---| -------- | ------------------------ | 
| | ![](https://i.imgur.com/y7QwKOI.png)     | |

**Comment by wolfmcnally** [comment]
This is expected behavior as even if the seed is identical the metadata may not be. It is up to the user to reconcile this.
