### ISSUE TITLE
Ability to upload a ur:crypto-response

### ISSUE THREAD

**Issue by Fonta1n3** [BlockchainCommons/GordianGuardian-iOS#46]
Currently the only way to pass Guardian a crypto-response is by scanning a QR code. Ideally I would like to test the crypto-request/response flow on the same device between two different apps, scanning a QR on the same device does not work. Adding the ability to upload the QR or paste the text would make testing this functionality a lot easier.

**Comment by wolfmcnally** [comment]
A paste button on the Scan screen that allows this has been added in 1.0 (9)
